### ISSUE TITLE
Do you still intend to adopt the zh-autoconvert Debian package?

### ISSUE THREAD

**Issue by anthonyfok** [suntong001/zh-autoconvert#1]
如題。 :-)

Seriously though, there is a renewed urgency of modernizing zh-autoconvert, as this message on https://packages.qa.debian.org/z/zh-autoconvert.html 

> Version 0.3.16-3 of zh-autoconvert is marked for autoremoval from testing on 2015-12-17.
> It is affected by RC bug [#800194](https://bugs.debian.org/800194).

You have voice your intent to adopt the zh-autoconvert package in Debian [#629015](https://bugs.debian.org/629015), but it would appear that your effort has ceased.  Do you have time to do so soon?  If not, I will continue working on getting zh-autoconvert in shape and upload it in the next few days, maybe borrowing what you have committed thus far in this repository, as I want to keep zh-autoconvert and its dependent packages from being removed from Debian.

Thanks!

Anthony Fok &lt;foka@debian.org&gt;

**Comment by anthonyfok** [comment]
Hi @suntong,

On second thought, I think I will just go ahead and finish upgrading the package and upload it, since I am almost done.  ;-)

I did end up using the new `debian/copyright` file that you nicely prepared, with the following details added:

```
Files: debian/*
Copyright: 1999–2000, 2015 Anthony Fok <foka@debian.org>
           2000–2009       Yu Guanghui <ygh@debian.org>
           2014–2015       Tong Sun <suntong001@users.sourceforge.net>
License: GPL-2.0+
Comment: See https://github.com/suntong/zh-autoconvert 
 for contributions by Tong Sun
```

I will likely use your hardening patch too.  :-)

but probably won't be using your other changes like removing all files related to the xchat plugins altogether.  Furthermore, I am using git-buildpackage and trying to include as many historical versions (with pristine-tar) as possible, with finely separated patch files inside `debian/patches`, etc.

If all goes well, I will be uploading 0.3.16-4 before I go to bed in a few hours.

Thanks again for your contributions!

Anthony

**Comment by suntong** [comment]
Yeah, I'm still intend to adopt it. My work stopped due to a technical issue that I stumbled upon and wasn't able to solve myself or from the Debian mentors. 

I just felt sorry to have such useful tools removed from Debian. 
Glad that you get it working.

**Comment by anthonyfok** [comment]
Hello @suntong,

Welcome to the Debian Chinese Team!  You request to join has been approved.

I have finally got zh-autoconvert (0.3.16-4) uploaded to Debian.  Took me longer than I expected (as usual, haha).  My packaging has been pushed to Debian Alioth server, and available for viewing and download at:
- https://anonscm.debian.org/cgit/chinese/zh-autoconvert.git

While my packaging is not perfect, hope you can find answers to at least some of the questions that you asked on debian-mentors back in 2014.

We make use of git-buildpackage (`gbp`) as our packaging tool of choice.  Unfortunately, we do not yet have any detailed documentation, but you can start by reading https://wiki.debian.org/DebianMultimedia/DevelopPackaging, as we follow a very similar process.

Make sure you subscribe to relevant mailing lists to keep in touch of what is happening, and to contact and discuss with other team members.

You may also find us on IRC at #debian-zh on OFTC, though not all of us are on there all the time.

Cheers,
Anthony
